In [1]:
import tensorflow as tf

In [6]:
tensor_one = tf.constant([[1,2,3], [4,5,7]], dtype="float32")

In [7]:
tensor_one.shape
tensor_one.dtype

tf.float32

In [8]:
tensor_one + 10

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 17.]], dtype=float32)>

In [9]:
tf.cast(tensor_one, dtype="float64")

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[1., 2., 3.],
       [4., 5., 7.]])>

In [10]:
tensor_var = tf.Variable([1, 2, 3])

In [13]:
tensor_var[0].assign(79)

<tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([79,  2,  3], dtype=int32)>